services:
  redis-server:
    image: redis
    command:
      - redis-server
    env_file:
      - .env
    restart: on-failure
    ports:
      - ":6379"
  mariadb-server:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
    env_file:
      - .env
    restart: on-failure
    ports:
      - "3306:3306"
  bot:
    build: .
    env_file:
      - .env
    restart: no
    depends_on:
      - redis-server
      - mariadb-server

